### ISSUE TITLE
How are you using it?

### ISSUE THREAD

**Issue by adricen** [ataylorme/gutenberg-codepen-embed#2]
Hello @ataylorme,

your plug-in seams to be exactly what I am looking for !
Since I am new to Guttemberg, I encounter a problems with embeding my pen inside wordpress now.

I was wondering how you were supposed to install your plug-in ?
I'll be pleased to document it inside your README in return.

Chears!

**Comment by ataylorme** [comment]
Hi @adricen,
I write this plugin as I was learning to create Gutenberg blocks in November 2018 and haven't updated it since. I'm not sure if it works with current versions of WordPress.

If you want to install it and test it out you can download a `.zip` file of the plugin at https://github.com/ataylorme/gutenberg-codepen-embed/archive/2.0.0.zip and upload that to WordPress.
